[project]
name = "papaya"
version = "1.0.0"
requires-python = ">=3.9"
dependencies = ["pandas (>=2.2.3,<3.0.0)", "pandera (>=0.24.0,<0.25.0)", "pytest (>=8.3.5,<9.0.0)"]

[tool.pytest.ini_options]
pythonpath = "src/"
testpaths = ["tests/"]
